# Generated by Django 5.1.4 on 2025-01-08 15:46

import resume.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='Enter your 10-digit phone number without the country code.', max_length=10, validators=[resume.models.validate_phone])),
            ],
        ),
    ]
